# Turns the base deployment with metrics support into a deployment for LVM mode.

bases:
- ../kubernetes-with-metrics

commonLabels:
  pmem-csi.intel.com/deployment: lvm-production

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: pmem-csi-intel-com-node
  path: ../patches/lvm-patch.yaml
