apiVersion: v1
kind: Service
metadata:
  name: pmem-csi-intel-com-scheduler
  namespace: pmem-csi
spec:
  selector:
    app.kubernetes.io/name: pmem-csi-controller
    app.kubernetes.io/instance: pmem-csi.intel.com
  type: ClusterIP
  ports:
  - targetPort: 8000
    port: 443
