apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: pmem-csi-intel-com-controller
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       StatefulSet
    name:       pmem-csi-intel-com-controller
  updatePolicy:
    updateMode: "Off"
