# We define our own service account and use this patch to remove
# the pre-defined one from the upstream rbac.yaml files.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-provisioner
  namespace: default
$patch: delete
