- op: add
  path: /spec/template/spec/containers/2/args/0
  value: "--enable-capacity"
- op: add
  path: /spec/template/spec/containers/2/args/1
  value: "--capacity-ownerref-level=0"
- op: add
  path: /spec/template/spec/containers/2/env/-
  value:
    name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
- op: add
  path: /spec/template/spec/containers/2/env/-
  value:
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
